# Generated by Django 6.1.1 on 2026-10-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAssortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('eyebrow', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link_label', models.CharField(max_length=100)),
                ('url_catalog', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Home assortment',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('marked', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('catalog_btn', models.CharField(max_length=100)),
                ('url_catalog', models.CharField(max_length=255)),
                ('history_btn', models.CharField(max_length=100)),
                ('url_history', models.CharField(max_length=255)),
                ('slider_image_label', models.CharField(max_length=255)),
                ('slider_previous_label', models.CharField(max_length=100)),
                ('slider_next_label', models.CharField(max_length=100)),
                ('slider_navigation_label', models.CharField(max_length=100)),
                ('slider_dot_label', models.CharField(max_length=100)),
                ('advantages', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name_plural': 'Homepage hero',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AssortmentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category_slug', models.CharField(max_length=50)),
                ('badge', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='homepage.homeassortment')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='homepage.homepagehero')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
