# Generated by Django 6.1.2 on 2026-10-06 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
            ],
            options={
                "verbose_name_plural": "FAQ",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FaqHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("heading", models.CharField(max_length=255)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name_plural": "FAQ heading",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="FaqSmall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("text", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "FAQ small",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PhilosophyHeading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("heading_1", models.CharField(max_length=255)),
                ("heading_2_before", models.CharField(blank=True, max_length=255)),
                ("heading_2_highlight", models.CharField(blank=True, max_length=255)),
                ("heading_2_after", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Philosophy headings",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PhilosophyText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("text", models.TextField()),
                ("btn", models.CharField(max_length=100)),
                ("slider_previous_label", models.CharField(max_length=100)),
                ("slider_next_label", models.CharField(max_length=100)),
                ("slider_image_label", models.CharField(max_length=100)),
                ("slider_navigation_label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Philosophy text",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lang", models.CharField(max_length=10)),
                ("value", models.IntegerField()),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("label", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Stats",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PhilosophyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("image", models.CharField(max_length=255)),
                ("alt", models.CharField(blank=True, max_length=255)),
                (
                    "philosophy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="homepage.philosophytext",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
