# Generated by Django 6.1.2 on 2026-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0002_faq_faqheading_faqsmall_philosophyheading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="faqheading",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="faqsmall",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="homeassortment",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="homepagehero",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="philosophyheading",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="philosophytext",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="stat",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
