# Generated by Django 6.1.2 on 2026-10-07 18:24

import base.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_media_image_paths'),
        ("homepage", "0003_alter_faq_lang_alter_faqheading_lang_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assortmentcard",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/homepage/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/homepage/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="philosophyimage",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/home/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
    ]
