# Generated by Django 6.1.1 on 2026-10-08 01:28

import base.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_images(apps, schema_editor):
    AssortmentCardImage = apps.get_model("homepage", "AssortmentCardImage")
    for obj in apps.get_model("homepage", "AssortmentCard").objects.exclude(image=""):
        AssortmentCardImage.objects.create(card=obj, order=0, image=obj.image.name)


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0004_image_file_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeassortment",
            name="slider_image_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homeassortment",
            name="slider_navigation_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homeassortment",
            name="slider_next_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="homeassortment",
            name="slider_previous_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name="AssortmentCardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to="images/homepage/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                            ),
                            base.fields.validate_image_size,
                        ],
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="homepage.assortmentcard",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_images, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="assortmentcard",
            name="image",
        ),
    ]
