# Generated by Django 6.1.1 on 2026-10-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('text_left', models.TextField()),
                ('text_right', models.TextField()),
                ('image_alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'About intro',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('brands_title', models.CharField(max_length=100)),
                ('breadcrumb_label', models.CharField(max_length=100)),
                ('home_label', models.CharField(max_length=100)),
                ('slider_previous_label', models.CharField(max_length=100)),
                ('slider_next_label', models.CharField(max_length=100)),
                ('slider_navigation_label', models.CharField(max_length=100)),
                ('slider_image_label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'About page labels',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPhilosophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('title_light', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'About philosophy',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPhilosophyFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'About philosophy facts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('subtitle', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('image', models.CharField(max_length=255)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'About production',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutQualityNaturalness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('card1_eyebrow', models.CharField(max_length=100)),
                ('card1_title', models.CharField(max_length=255)),
                ('card1_paragraphs', models.JSONField(blank=True, default=list)),
                ('card2_eyebrow', models.CharField(max_length=100)),
                ('card2_title', models.CharField(max_length=255)),
                ('card2_paragraph', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'About quality naturalness',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('prev_label', models.CharField(max_length=100)),
                ('next_label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'About showcase',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutWhyTrustUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'About why trust us',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IntroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('intro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='about.aboutintro')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=10)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='about.aboutproduction')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255)),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.aboutshowcase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TrustStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('label', models.TextField()),
                ('is_highlighted', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='about.aboutwhytrustus')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
