# Generated by Django 6.1.1 on 2026-10-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('card_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('image_alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Brands',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExportCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('left_text', models.TextField()),
                ('right_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Export cooperation',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OurFactory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=100)),
                ('title_green', models.CharField(max_length=255)),
                ('title_black', models.CharField(max_length=255)),
                ('first_text', models.TextField()),
                ('second_text', models.TextField()),
                ('bottom_left_text', models.TextField()),
                ('bottom_right_text', models.TextField()),
                ('slider_previous_label', models.CharField(max_length=100)),
                ('slider_next_label', models.CharField(max_length=100)),
                ('slider_image_label', models.CharField(max_length=100)),
                ('slider_navigation_label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Our factory',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WeBelieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('title_end', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'We believe',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='productiondirection',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.CreateModel(
            name='FactorySlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='about.ourfactory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FactoryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='about.ourfactory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
