# Generated by Django 6.1.2 on 2026-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_brand_exportcooperation_ourfactory_webelieve_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutintro",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutpagelabel",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutphilosophy",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutphilosophyfact",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutproduction",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutqualitynaturalness",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutshowcase",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="aboutwhytrustus",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="exportcooperation",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ourfactory",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="webelieve",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="brand",
            constraint=models.UniqueConstraint(
                fields=("lang", "code"), name="unique_brand_lang_code"
            ),
        ),
    ]
