# Generated by Django 6.1.2 on 2026-10-07 18:24

import base.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_media_image_paths'),
        ("about", "0003_alter_aboutintro_lang_alter_aboutpagelabel_lang_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutproduction",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/about-us/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/brands/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="factorygalleryimage",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/about-us/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="factoryslide",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/about-us/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="introslide",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/about-us/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="showcaseimage",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/about-us/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
    ]
