# Generated by Django 6.1.1 on 2026-10-08 01:28

import base.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def copy_images(apps, schema_editor):
    ProductionImage = apps.get_model("about", "ProductionImage")
    for obj in apps.get_model("about", "AboutProduction").objects.exclude(image=""):
        ProductionImage.objects.create(production=obj, order=0, image=obj.image.name)
    BrandImage = apps.get_model("about", "BrandImage")
    for obj in apps.get_model("about", "Brand").objects.exclude(image=""):
        BrandImage.objects.create(brand=obj, order=0, image=obj.image.name)


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0004_image_file_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to="images/brands/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                            ),
                            base.fields.validate_image_size,
                        ],
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="about.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to="images/about-us/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                            ),
                            base.fields.validate_image_size,
                        ],
                    ),
                ),
                (
                    "production",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="about.aboutproduction",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_images, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="aboutproduction",
            name="image",
        ),
        migrations.RemoveField(
            model_name="brand",
            name="image",
        ),
    ]
