# Generated by Django 6.1.1 on 2026-10-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('address_label', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.TextField(blank=True)),
                ('email_label', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('social_label', models.CharField(max_length=100)),
                ('map_url', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Contact info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('breadcrumb_home', models.CharField(max_length=100)),
                ('breadcrumb_contact', models.CharField(max_length=100)),
                ('breadcrumb_label', models.CharField(max_length=100)),
                ('form_title', models.CharField(max_length=255)),
                ('name_label', models.CharField(max_length=100)),
                ('email_label', models.CharField(max_length=100)),
                ('phone_label', models.CharField(max_length=100)),
                ('message_label', models.CharField(max_length=100)),
                ('submit_label', models.CharField(max_length=100)),
                ('sending_label', models.CharField(max_length=100)),
                ('success_message', models.CharField(max_length=255)),
                ('error_message', models.CharField(max_length=255)),
                ('map_title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Contact page contents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(max_length=100)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='contact.contactinfo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
