# Generated by Django 6.1.2 on 2026-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactinfo",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="contactpagecontent",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
