# Generated by Django 6.1.2 on 2026-10-07 18:24

import base.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_media_image_paths'),
        ("contact", "0002_alter_contactinfo_lang_alter_contactpagecontent_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactsociallink",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/contact/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
    ]
