# Generated by Django 6.1.1 on 2026-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Partner CTA',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='footerlabel',
            name='links_label',
            field=models.CharField(default='', max_length=255),
        ),
    ]
