# Generated by Django 6.1.2 on 2026-10-07 18:24

import base.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_media_image_paths'),
        ("footer", "0003_alter_footerlabel_lang_alter_partnercta_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerlabel",
            name="image",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="images/footer/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="image",
            field=models.FileField(
                blank=True,
                max_length=255,
                null=True,
                upload_to="images/footer/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
    ]
