# Generated by Django 6.1.1 on 2026-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='images/categories/dried-fruits.jpg')),
                ('product_count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Headerlabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('all_products', models.CharField(max_length=50)),
                ('products_toggle_label', models.CharField(max_length=80)),
                ('menu_label', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Headerlabels',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='images/header/')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='images/header/')),
            ],
            options={
                'verbose_name_plural': 'Logo',
            },
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Navbar',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=10)),
                ('label', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
