# Generated by Django 6.1.1 on 2026-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='logo',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
