# Generated by Django 6.1.2 on 2026-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"ordering": ["id"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="headerlabels",
            options={"ordering": ["id"], "verbose_name_plural": "Headerlabels"},
        ),
        migrations.AlterModelOptions(
            name="languages",
            options={"ordering": ["id"], "verbose_name_plural": "Languages"},
        ),
        migrations.AlterModelOptions(
            name="navbar",
            options={"ordering": ["id"], "verbose_name_plural": "Navbar"},
        ),
        migrations.AlterModelOptions(
            name="tags",
            options={"ordering": ["id"], "verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="categories",
            name="image",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="categories",
            name="product_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="headerlabels",
            name="all_products",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="headerlabels",
            name="lang",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="headerlabels",
            name="menu_label",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="headerlabels",
            name="products_toggle_label",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="languages",
            name="image",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="languages",
            name="label",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="logo",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="lang",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="url",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tags",
            name="code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tags",
            name="icon",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="tags",
            name="label",
            field=models.CharField(max_length=100),
        ),
    ]
