# Generated by Django 6.1.1 on 2026-09-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0002_alter_logo_image_alter_logo_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.FileField(upload_to='images/header/'),
        ),
    ]
