# Generated by Django 6.1.2 on 2026-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("header", "0002_alter_categories_options_alter_headerlabels_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="headerlabels",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="languages",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="navbar",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="categories",
            constraint=models.UniqueConstraint(
                fields=("lang", "slug"), name="unique_category_lang_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="navbar",
            constraint=models.UniqueConstraint(
                fields=("lang", "url"), name="unique_navbar_lang_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="tags",
            constraint=models.UniqueConstraint(
                fields=("lang", "code"), name="unique_tag_lang_code"
            ),
        ),
    ]
