# Generated by Django 6.1.2 on 2026-10-07 18:24

import base.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_media_image_paths'),
        ("header", "0003_alter_categories_lang_alter_categories_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/categories/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="languages",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/header/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="logo",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/header/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
    ]
