# Generated by Django 6.1.1 on 2026-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0004_alter_languages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
