# Generated by Django 6.1.1 on 2026-09-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0005_alter_languages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languages',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/header/'),
        ),
    ]
