# Generated by Django 6.1.1 on 2026-09-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('header', '0007_navbar_alter_languages_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='headerlabels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=20)),
                ('all_products', models.CharField(max_length=50)),
                ('products_toggle_label', models.CharField(max_length=80)),
                ('menu_label', models.CharField(max_length=10)),
            ],
        ),
    ]
