# Generated by Django 6.1.1 on 2026-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Export countries',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GeographyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('breadcrumb_home', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField()),
                ('description_1', models.TextField()),
                ('description_highlight', models.TextField()),
                ('description_2', models.TextField()),
                ('countries_title', models.CharField(max_length=255)),
                ('bottom_text', models.TextField()),
                ('countries_more', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Geography contents',
                'ordering': ['id'],
            },
        ),
    ]
