# Generated by Django 6.1.2 on 2026-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportcountry",
            name="code",
            field=models.CharField(max_length=50),
        ),
    ]
