# Generated by Django 6.1.2 on 2026-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0002_alter_exportcountry_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportcountry",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="geographycontent",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="exportcountry",
            constraint=models.UniqueConstraint(
                fields=("lang", "code"), name="unique_country_lang_code"
            ),
        ),
    ]
