# Generated by Django 6.1.1 on 2026-10-05 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('slug', models.CharField(max_length=100)),
                ('category_slug', models.CharField(max_length=50)),
                ('weight_value', models.IntegerField()),
                ('weight_unit', models.CharField(max_length=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('name', models.CharField(max_length=200)),
                ('composition', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('default_variant', models.CharField(blank=True, max_length=10)),
                ('tastes_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('flavor', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=255)),
                ('box_image', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Product variants',
                'ordering': ['id'],
            },
        ),
    ]
