# Generated by Django 6.1.1 on 2026-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('home_label', models.CharField(max_length=100)),
                ('catalog_label', models.CharField(max_length=100)),
                ('composition_eyebrow', models.CharField(max_length=100)),
                ('close_button', models.CharField(max_length=100)),
                ('previous_image', models.CharField(max_length=100)),
                ('next_image', models.CharField(max_length=100)),
                ('image_label', models.CharField(max_length=100)),
                ('variants_label', models.CharField(max_length=100)),
                ('composition_button', models.CharField(max_length=100)),
                ('weight_unit', models.CharField(max_length=20)),
                ('taste_unit', models.CharField(max_length=20)),
                ('breadcrumb_label', models.CharField(max_length=100)),
                ('all_products_label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product page labels',
                'ordering': ['id'],
            },
        ),
    ]
