# Generated by Django 6.1.2 on 2026-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productpagelabel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("icon", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name_plural": "Tag icons",
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="tastes_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
