# Generated by Django 6.1.2 on 2026-10-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_tagicon_alter_product_tastes_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category_slug",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="productpagelabel",
            name="lang",
            field=models.CharField(
                choices=[("am", "Հայերեն"), ("ru", "Русский"), ("en", "English")],
                db_index=True,
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="tagicon",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("lang", "slug"), name="unique_product_lang_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "code"), name="unique_variant_product_code"
            ),
        ),
    ]
