# Generated by Django 6.1.2 on 2026-10-07 18:24

import base.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def to_file_name(path):
    if path.startswith("/media/"):
        return path[len("/media/"):]
    return path.lstrip("/")


def images_to_gallery(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    ProductImage = apps.get_model("product", "ProductImage")
    for product in Product.objects.all():
        for order, path in enumerate(product.images or []):
            if path:
                ProductImage.objects.create(product=product, order=order, image=to_file_name(path))


def gallery_to_images(apps, schema_editor):
    Product = apps.get_model("product", "Product")
    for product in Product.objects.all():
        names = [item.image.name for item in product.gallery.order_by("order", "id")]
        product.images = [name if name.startswith("/") else "/media/" + name for name in names]
        product.save(update_fields=["images"])


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_media_image_paths"),
        ("product", "0004_alter_product_category_slug_alter_product_lang_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="box_image",
            field=models.FileField(
                max_length=255,
                upload_to="images/products/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.FileField(
                max_length=255,
                upload_to="images/products/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                    ),
                    base.fields.validate_image_size,
                ],
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.FileField(
                        max_length=255,
                        upload_to="images/products/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp", "gif", "svg"]
                            ),
                            base.fields.validate_image_size,
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(images_to_gallery, gallery_to_images),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
    ]
